name: Shiny Container App service deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t docker.io/vibbioinfocore/r-shiny-nc:${{ github.sha }}
        docker push docker.io/vibbioinfocore/r-shiny-mec:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-dev-bitsmec'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'docker.io/vibbioinfocore/r-shiny-mec:${{ github.sha }}'

